# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  push:
    paths:
    - 'Supercell.Laser.Logic/**'
    - 'Supercell.Laser.Server/**'
    - 'Supercell.Laser.Titan/**'
  pull_request:
    paths:
    - 'Supercell.Laser.Logic/**'
    - 'Supercell.Laser.Server/**'
    - 'Supercell.Laser.Titan/**'
  workflow_dispatch:
 
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dotnet-packaging
      run: dotnet tool install --global dotnet-zip
    - name: Restore dependencies
      run: cd Supercell.Laser.Server && dotnet restore Supercell.Laser.Server.csproj
    - name: Build
      run: cd Supercell.Laser.Server && dotnet build Supercell.Laser.Server.csproj --no-restore
    - name: packages
      run: cd Supercell.Laser.Server && dotnet zip install && dotnet zip
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Server
        path: Supercell.Laser.Server/bin/Debug/net6.0/Supercell.Laser.Server.1.0.0.zip
